CREATE TABLE coin_streams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Verweis direkt auf die Adresse (Lesbar & Schnell)
    token_address VARCHAR(64) NOT NULL REFERENCES discovered_coins(token_address) ON DELETE CASCADE,
    
    -- Steuerung
    current_phase_id INT REFERENCES ref_coin_phases(id) DEFAULT 1,
    is_active BOOLEAN DEFAULT TRUE,
    
    -- Neue Spalte direkt hier integriert
    is_graduated BOOLEAN DEFAULT FALSE,
    
    -- Monitoring
    started_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Verhindert doppelte Streams für denselben Coin
    CONSTRAINT unique_active_stream UNIQUE (token_address)
);