"""
Automatische Datenbank-Migrationen für pump-metric
Erkennt fehlende Tabellen/Spalten und erstellt sie automatisch beim Start
"""
import asyncio
import asyncpg
import os
from pathlib import Path

DB_DSN = os.getenv("DB_DSN", "postgresql://postgres:9HVxi6hN6j7xpmqUx84o@100.118.155.75:5432/crypto")

async def check_and_create_schema(pool=None):
    """Prüft ob alle benötigten Tabellen existieren und erstellt sie falls nötig"""
    try:
        if pool:
            conn = await pool.acquire()
            try:
                await _check_schema(conn)
            finally:
                await pool.release(conn)
        else:
            conn = await asyncpg.connect(DB_DSN)
            try:
                await _check_schema(conn)
            finally:
                await conn.close()
        
        return True
        
    except Exception as e:
        print(f"❌ Fehler beim Schema-Check: {e}", flush=True)
        return False

async def _check_schema(conn):
        
        print("🔍 Prüfe Datenbank-Schema...", flush=True)
        
        # Prüfe coin_metrics Tabelle
        table_exists = await conn.fetchval("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'coin_metrics'
            )
        """)
        
        if not table_exists:
            print("📊 Erstelle coin_metrics Tabelle...", flush=True)
            await conn.execute("""
                CREATE TABLE IF NOT EXISTS coin_metrics (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    mint VARCHAR(64) NOT NULL, 
                    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
                    phase_id_at_time INT,
                    price_open NUMERIC,
                    price_high NUMERIC,
                    price_low NUMERIC,
                    price_close NUMERIC,
                    market_cap_close NUMERIC, 
                    bonding_curve_pct NUMERIC, 
                    virtual_sol_reserves NUMERIC,
                    is_koth BOOLEAN DEFAULT FALSE,
                    volume_sol NUMERIC,
                    buy_volume_sol NUMERIC,
                    sell_volume_sol NUMERIC,
                    num_buys INT,
                    num_sells INT,
                    unique_wallets INT,
                    num_micro_trades INT,
                    dev_sold_amount NUMERIC DEFAULT 0,
                    max_single_buy_sol NUMERIC DEFAULT 0,
                    max_single_sell_sol NUMERIC DEFAULT 0
                );
            """)
            await conn.execute("""
                CREATE INDEX IF NOT EXISTS idx_metrics_mint_time ON coin_metrics(mint, timestamp);
            """)
            print("✅ coin_metrics Tabelle erstellt", flush=True)
        else:
            # Prüfe ob alle Spalten vorhanden sind
            columns = await conn.fetch("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name = 'coin_metrics'
            """)
            existing_columns = {row['column_name'] for row in columns}
            required_columns = {
                'id', 'mint', 'timestamp', 'phase_id_at_time', 'price_open', 'price_high',
                'price_low', 'price_close', 'market_cap_close', 'bonding_curve_pct',
                'virtual_sol_reserves', 'is_koth', 'volume_sol', 'buy_volume_sol',
                'sell_volume_sol', 'num_buys', 'num_sells', 'unique_wallets',
                'num_micro_trades', 'dev_sold_amount', 'max_single_buy_sol', 'max_single_sell_sol'
            }
            
            missing_columns = required_columns - existing_columns
            if missing_columns:
                print(f"⚠️  Fehlende Spalten in coin_metrics: {missing_columns}", flush=True)
                # Füge fehlende Spalten hinzu
                for col in missing_columns:
                    if col == 'id':
                        continue  # Primary Key wird nicht nachträglich hinzugefügt
                    elif col in ['dev_sold_amount', 'max_single_buy_sol', 'max_single_sell_sol']:
                        await conn.execute(f"ALTER TABLE coin_metrics ADD COLUMN IF NOT EXISTS {col} NUMERIC DEFAULT 0;")
                    elif col == 'is_koth':
                        await conn.execute(f"ALTER TABLE coin_metrics ADD COLUMN IF NOT EXISTS {col} BOOLEAN DEFAULT FALSE;")
                    elif col in ['num_buys', 'num_sells', 'unique_wallets', 'num_micro_trades', 'phase_id_at_time']:
                        await conn.execute(f"ALTER TABLE coin_metrics ADD COLUMN IF NOT EXISTS {col} INT;")
                    elif col == 'timestamp':
                        await conn.execute(f"ALTER TABLE coin_metrics ADD COLUMN IF NOT EXISTS {col} TIMESTAMP WITH TIME ZONE DEFAULT NOW();")
                    elif col == 'mint':
                        await conn.execute(f"ALTER TABLE coin_metrics ADD COLUMN IF NOT EXISTS {col} VARCHAR(64) NOT NULL DEFAULT '';")
                    else:
                        await conn.execute(f"ALTER TABLE coin_metrics ADD COLUMN IF NOT EXISTS {col} NUMERIC;")
                    print(f"✅ Spalte {col} hinzugefügt", flush=True)
        
        # Prüfe Index
        index_exists = await conn.fetchval("""
            SELECT EXISTS (
                SELECT FROM pg_indexes 
                WHERE tablename = 'coin_metrics' 
                AND indexname = 'idx_metrics_mint_time'
            )
        """)
        if not index_exists:
            print("📊 Erstelle Index idx_metrics_mint_time...", flush=True)
            await conn.execute("""
                CREATE INDEX idx_metrics_mint_time ON coin_metrics(mint, timestamp);
            """)
            print("✅ Index erstellt", flush=True)
        
        # Prüfe coin_streams Tabelle (wird von pump-discover erstellt, aber prüfen wir trotzdem)
        streams_exists = await conn.fetchval("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'coin_streams'
            )
        """)
        
        if not streams_exists:
            print("⚠️  coin_streams Tabelle nicht gefunden - wird von pump-discover erstellt", flush=True)
        else:
            print("✅ coin_streams Tabelle vorhanden", flush=True)
        
        # Prüfe discovered_coins Tabelle
        discovered_exists = await conn.fetchval("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'discovered_coins'
            )
        """)
        
        if not discovered_exists:
            print("⚠️  discovered_coins Tabelle nicht gefunden - wird von pump-discover erstellt", flush=True)
        else:
            print("✅ discovered_coins Tabelle vorhanden", flush=True)
        
        # Prüfe ref_coin_phases Tabelle
        phases_exists = await conn.fetchval("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'ref_coin_phases'
            )
        """)
        
        if not phases_exists:
            print("⚠️  ref_coin_phases Tabelle nicht gefunden - wird von pump-discover erstellt", flush=True)
        else:
            print("✅ ref_coin_phases Tabelle vorhanden", flush=True)
        
        print("✅ Datenbank-Schema-Check abgeschlossen", flush=True)

if __name__ == "__main__":
    asyncio.run(check_and_create_schema())

