-- ============================================================================
-- PUMP METRIC - Vollständiges Schema für coin_metrics Tabelle
-- ============================================================================
-- Dieses Schema enthält ALLE Metriken, die im System berechnet und gespeichert werden.
-- Siehe auch: UI Info-Seite für detaillierte Erklärungen
-- ============================================================================

-- Tabelle löschen (falls vorhanden - VORSICHT: Löscht alle Daten!)
-- DROP TABLE IF EXISTS coin_metrics CASCADE;

-- Vollständige coin_metrics Tabelle erstellen
CREATE TABLE IF NOT EXISTS coin_metrics (
    -- ============================================================================
    -- 1. IDENTIFIKATION & ZEITPUNKT
    -- ============================================================================
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mint VARCHAR(64) NOT NULL,                    -- Token-Adresse (Mint)
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),  -- Zeitpunkt (Berliner Zeit)
    phase_id_at_time INT,                         -- Phase zum Zeitpunkt der Metrik
    
    -- ============================================================================
    -- 2. PREIS & BEWERTUNG (OHLC)
    -- ============================================================================
    price_open NUMERIC(24, 9),                    -- Erster Preis im Intervall
    price_high NUMERIC(24, 9),                    -- Höchster Preis im Intervall
    price_low NUMERIC(24, 9),                     -- Niedrigster Preis im Intervall
    price_close NUMERIC(24, 9),                   -- Letzter Preis im Intervall
    market_cap_close NUMERIC(24, 9),              -- Market Cap (price_close * 1.000.000.000)
    
    -- ============================================================================
    -- 3. PUMP.FUN MECHANIK
    -- ============================================================================
    bonding_curve_pct NUMERIC(10, 4),             -- Bonding Curve Prozentsatz: (v_sol / 85.0) * 100
    virtual_sol_reserves NUMERIC(24, 9),          -- Aktuelles virtuelles SOL in Bonding Curve
    is_koth BOOLEAN DEFAULT FALSE,                -- King of the Hill: Market Cap > 30.000 SOL
    
    -- ============================================================================
    -- 4. VOLUMEN & FLUSS
    -- ============================================================================
    volume_sol NUMERIC(24, 9),                    -- Gesamt-Volumen (Buy + Sell)
    buy_volume_sol NUMERIC(24, 9),                -- Nur Buy-Volumen
    sell_volume_sol NUMERIC(24, 9),               -- Nur Sell-Volumen
    net_volume_sol NUMERIC(24, 9) DEFAULT 0,      -- Netto-Volumen (Delta): buy_volume_sol - sell_volume_sol
    
    -- ============================================================================
    -- 5. ORDER-STRUKTUR & BOT-SCHUTZ
    -- ============================================================================
    num_buys INT DEFAULT 0,                       -- Anzahl Buy-Trades
    num_sells INT DEFAULT 0,                      -- Anzahl Sell-Trades
    unique_wallets INT DEFAULT 0,                 -- Anzahl verschiedener Wallets (für Wash-Trading-Erkennung)
    num_micro_trades INT DEFAULT 0,               -- Anzahl Trades < 0.01 SOL (Volume-Bot-Erkennung)
    
    -- ============================================================================
    -- 6. WHALE WATCHING & MAXIMALE TRADES
    -- ============================================================================
    max_single_buy_sol NUMERIC(24, 9) DEFAULT 0,  -- Größter einzelner Buy-Trade
    max_single_sell_sol NUMERIC(24, 9) DEFAULT 0, -- Größter einzelner Sell-Trade
    
    -- Whale-Tracking (Trades >= WHALE_THRESHOLD_SOL, Standard: 1.0 SOL)
    whale_buy_volume_sol NUMERIC(24, 9) DEFAULT 0,    -- Volumen von Buy-Trades >= 1.0 SOL
    whale_sell_volume_sol NUMERIC(24, 9) DEFAULT 0,   -- Volumen von Sell-Trades >= 1.0 SOL
    num_whale_buys INTEGER DEFAULT 0,                 -- Anzahl Whale-Buy-Trades
    num_whale_sells INTEGER DEFAULT 0,                 -- Anzahl Whale-Sell-Trades
    
    -- ============================================================================
    -- 7. DEV-TRACKING (KRITISCH FÜR RUG-PULL-ERKENNUNG)
    -- ============================================================================
    dev_sold_amount NUMERIC(24, 9) DEFAULT 0,    -- Verkauftes Volumen vom Creator (traderPublicKey == creator_address)
                                                   -- WICHTIG: Zeigt ob Developer verkauft (Rug-Pull-Indikator)
    
    -- ============================================================================
    -- 8. ERWEITERTE METRIKEN (Volatilität & Durchschnitte)
    -- ============================================================================
    volatility_pct NUMERIC(10, 4) DEFAULT 0,      -- Volatilität: ((price_high - price_low) / price_open) * 100
                                                   -- Zeigt relative Preis-Schwankung im Intervall
    avg_trade_size_sol NUMERIC(24, 9) DEFAULT 0,  -- Durchschnittliche Trade-Größe: volume_sol / (num_buys + num_sells)
    
    -- ============================================================================
    -- 9. RATIO-METRIKEN (Bot-Spam vs. echtes Interesse)
    -- ============================================================================
    buy_pressure_ratio NUMERIC(5, 4) DEFAULT 0,  -- Buy-Pressure: buy_volume_sol / (buy_volume_sol + sell_volume_sol)
                                                   -- 0.0 = nur Sells, 1.0 = nur Buys, 0.5 = ausgeglichen
    unique_signer_ratio NUMERIC(5, 4) DEFAULT 0  -- Unique-Signer-Ratio: unique_wallets / (num_buys + num_sells)
                                                   -- Niedrig (z.B. 0.02) = Wash-Trading, Hoch (z.B. 0.8) = organisches Wachstum
);

-- ============================================================================
-- INDIZES FÜR PERFORMANCE
-- ============================================================================

-- Primärer Index: Schnelle Suche nach Coin und Zeitpunkt
CREATE INDEX IF NOT EXISTS idx_metrics_mint_time ON coin_metrics(mint, timestamp DESC);

-- Index für Zeitbereichs-Abfragen
CREATE INDEX IF NOT EXISTS idx_metrics_timestamp ON coin_metrics(timestamp DESC);

-- Index für Phase-basierte Abfragen
CREATE INDEX IF NOT EXISTS idx_metrics_phase ON coin_metrics(phase_id_at_time);

-- Index für KOTH-Coins
CREATE INDEX IF NOT EXISTS idx_metrics_koth ON coin_metrics(is_koth) WHERE is_koth = TRUE;

-- ============================================================================
-- KOMMENTARE FÜR DOKUMENTATION
-- ============================================================================

COMMENT ON TABLE coin_metrics IS 'Vollständige Metriken für jeden Coin in jedem Intervall. Enthält OHLC, Volumen, Whale-Tracking, Dev-Tracking und erweiterte Metriken.';

COMMENT ON COLUMN coin_metrics.mint IS 'Token-Adresse (Mint) - Identifikation des Coins';
COMMENT ON COLUMN coin_metrics.timestamp IS 'Zeitpunkt der Metrik (Berliner Zeit)';
COMMENT ON COLUMN coin_metrics.phase_id_at_time IS 'Phase zum Zeitpunkt der Metrik (0, 1, 2, etc.)';

COMMENT ON COLUMN coin_metrics.price_open IS 'Erster Preis im Intervall';
COMMENT ON COLUMN coin_metrics.price_high IS 'Höchster Preis im Intervall';
COMMENT ON COLUMN coin_metrics.price_low IS 'Niedrigster Preis im Intervall';
COMMENT ON COLUMN coin_metrics.price_close IS 'Letzter Preis im Intervall';
COMMENT ON COLUMN coin_metrics.market_cap_close IS 'Market Cap: price_close * 1.000.000.000';

COMMENT ON COLUMN coin_metrics.bonding_curve_pct IS 'Bonding Curve Prozentsatz: (virtual_sol_reserves / 85.0) * 100. 100% = Graduierung zu Raydium';
COMMENT ON COLUMN coin_metrics.virtual_sol_reserves IS 'Aktuelles virtuelles SOL in der Bonding Curve';
COMMENT ON COLUMN coin_metrics.is_koth IS 'King of the Hill: TRUE wenn Market Cap > 30.000 SOL (erscheint in Pump.fun Top-Liste)';

COMMENT ON COLUMN coin_metrics.volume_sol IS 'Gesamt-Volumen: buy_volume_sol + sell_volume_sol';
COMMENT ON COLUMN coin_metrics.buy_volume_sol IS 'Nur Buy-Volumen (Käufe)';
COMMENT ON COLUMN coin_metrics.sell_volume_sol IS 'Nur Sell-Volumen (Verkäufe)';
COMMENT ON COLUMN coin_metrics.net_volume_sol IS 'Netto-Volumen (Delta): buy_volume_sol - sell_volume_sol. Positiv = Kaufdruck, Negativ = Verkaufsdruck';

COMMENT ON COLUMN coin_metrics.num_buys IS 'Anzahl Buy-Trades im Intervall';
COMMENT ON COLUMN coin_metrics.num_sells IS 'Anzahl Sell-Trades im Intervall';
COMMENT ON COLUMN coin_metrics.unique_wallets IS 'Anzahl verschiedener Wallets. Niedriges Verhältnis zu num_buys+num_sells = Wash-Trading';
COMMENT ON COLUMN coin_metrics.num_micro_trades IS 'Anzahl Trades < 0.01 SOL (Volume-Bot-Erkennung)';

COMMENT ON COLUMN coin_metrics.max_single_buy_sol IS 'Größter einzelner Buy-Trade im Intervall';
COMMENT ON COLUMN coin_metrics.max_single_sell_sol IS 'Größter einzelner Sell-Trade im Intervall';

COMMENT ON COLUMN coin_metrics.whale_buy_volume_sol IS 'Volumen von Buy-Trades >= WHALE_THRESHOLD_SOL (Standard: 1.0 SOL)';
COMMENT ON COLUMN coin_metrics.whale_sell_volume_sol IS 'Volumen von Sell-Trades >= WHALE_THRESHOLD_SOL (Standard: 1.0 SOL)';
COMMENT ON COLUMN coin_metrics.num_whale_buys IS 'Anzahl Buy-Trades >= WHALE_THRESHOLD_SOL';
COMMENT ON COLUMN coin_metrics.num_whale_sells IS 'Anzahl Sell-Trades >= WHALE_THRESHOLD_SOL';

COMMENT ON COLUMN coin_metrics.dev_sold_amount IS 'KRITISCH: Verkauftes Volumen vom Creator (traderPublicKey == creator_address). Zeigt Rug-Pull-Risiko. 0 = Creator hält, >0 = Creator verkauft';

COMMENT ON COLUMN coin_metrics.volatility_pct IS 'Volatilität: ((price_high - price_low) / price_open) * 100. Zeigt relative Preis-Schwankung im Intervall';
COMMENT ON COLUMN coin_metrics.avg_trade_size_sol IS 'Durchschnittliche Trade-Größe: volume_sol / (num_buys + num_sells)';

COMMENT ON COLUMN coin_metrics.buy_pressure_ratio IS 'Buy-Pressure: buy_volume_sol / (buy_volume_sol + sell_volume_sol). 0.0 = nur Sells, 1.0 = nur Buys, 0.5 = ausgeglichen';
COMMENT ON COLUMN coin_metrics.unique_signer_ratio IS 'Unique-Signer-Ratio: unique_wallets / (num_buys + num_sells). Niedrig (0.02) = Wash-Trading, Hoch (0.8) = organisches Wachstum';

-- ============================================================================
-- BEISPIEL-ABFRAGEN
-- ============================================================================

-- Beispiel 1: Neueste Metriken für einen Coin
/*
SELECT 
    timestamp,
    price_close,
    volume_sol,
    buy_volume_sol,
    sell_volume_sol,
    net_volume_sol,
    volatility_pct,
    whale_buy_volume_sol,
    dev_sold_amount
FROM coin_metrics
WHERE mint = 'DEIN_MINT_HIER'
ORDER BY timestamp DESC
LIMIT 10;
*/

-- Beispiel 2: Coins mit hoher Volatilität
/*
SELECT 
    mint,
    timestamp,
    volatility_pct,
    price_open,
    price_high,
    price_low,
    price_close
FROM coin_metrics
WHERE volatility_pct > 50
ORDER BY volatility_pct DESC
LIMIT 20;
*/

-- Beispiel 3: Whale-Aktivität
/*
SELECT 
    mint,
    timestamp,
    whale_buy_volume_sol,
    whale_sell_volume_sol,
    num_whale_buys,
    num_whale_sells
FROM coin_metrics
WHERE whale_buy_volume_sol > 10 OR whale_sell_volume_sol > 10
ORDER BY timestamp DESC
LIMIT 20;
*/

-- Beispiel 4: Dev-Tracking (Rug-Pull-Erkennung)
/*
SELECT 
    mint,
    timestamp,
    dev_sold_amount,
    sell_volume_sol,
    buy_pressure_ratio
FROM coin_metrics
WHERE dev_sold_amount > 0
ORDER BY dev_sold_amount DESC
LIMIT 20;
*/

-- Beispiel 5: Buy-Pressure Analyse
/*
SELECT 
    mint,
    timestamp,
    buy_pressure_ratio,
    buy_volume_sol,
    sell_volume_sol,
    unique_signer_ratio
FROM coin_metrics
WHERE buy_pressure_ratio > 0.7  -- Starker Kaufdruck
ORDER BY timestamp DESC
LIMIT 20;
*/

-- ============================================================================
-- ENDE DES SCHEMAS
-- ============================================================================

