CREATE TABLE coin_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mint VARCHAR(64) NOT NULL, 
    
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    phase_id_at_time INT,
    
    -- 1. PREIS & BEWERTUNG
    price_open NUMERIC,
    price_high NUMERIC,
    price_low NUMERIC,
    price_close NUMERIC,
    market_cap_close NUMERIC, 
    
    -- 2. PUMP.FUN MECHANIK
    bonding_curve_pct NUMERIC, 
    virtual_sol_reserves NUMERIC,
    
    -- [NEU & WICHTIG] Sichtbarkeits-Boost
    is_koth BOOLEAN DEFAULT FALSE,  -- True wenn MC > 30k (King of Hill)
    
    -- 3. VOLUMEN & FLUSS
    volume_sol NUMERIC,
    buy_volume_sol NUMERIC,
    sell_volume_sol NUMERIC,
    
    -- 4. ORDER-STRUKTUR & BOT-SCHUTZ
    num_buys INT,
    num_sells INT,
    unique_wallets INT,             -- Verhältnis zu num_buys zeigt Wash-Trading
    num_micro_trades INT,           -- Zeigt Volume-Bots
    
    -- 5. WHALE WATCHING
    dev_sold_amount NUMERIC DEFAULT 0,
    max_single_buy_sol NUMERIC DEFAULT 0,
    max_single_sell_sol NUMERIC DEFAULT 0
);

CREATE INDEX idx_metrics_mint_time ON coin_metrics(mint, timestamp);