-- ============================================================================
-- PUMP METRIC - Schema für coin_metrics Tabelle
-- ============================================================================
-- HINWEIS: Dies ist eine vereinfachte Version. Für das vollständige Schema
-- mit allen Kommentaren und Beispiel-Abfragen siehe: coin_metrics_complete.sql
-- ============================================================================

CREATE TABLE IF NOT EXISTS coin_metrics (
    -- Identifikation & Zeitpunkt
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mint VARCHAR(64) NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    phase_id_at_time INT,
    
    -- Preis & Bewertung (OHLC)
    price_open NUMERIC(24, 9),
    price_high NUMERIC(24, 9),
    price_low NUMERIC(24, 9),
    price_close NUMERIC(24, 9),
    market_cap_close NUMERIC(24, 9),
    
    -- Pump.fun Mechanik
    bonding_curve_pct NUMERIC(10, 4),
    virtual_sol_reserves NUMERIC(24, 9),
    is_koth BOOLEAN DEFAULT FALSE,
    
    -- Volumen & Fluss
    volume_sol NUMERIC(24, 9),
    buy_volume_sol NUMERIC(24, 9),
    sell_volume_sol NUMERIC(24, 9),
    net_volume_sol NUMERIC(24, 9) DEFAULT 0,
    
    -- Order-Struktur & Bot-Schutz
    num_buys INT DEFAULT 0,
    num_sells INT DEFAULT 0,
    unique_wallets INT DEFAULT 0,
    num_micro_trades INT DEFAULT 0,
    
    -- Whale Watching & Maximal Trades
    max_single_buy_sol NUMERIC(24, 9) DEFAULT 0,
    max_single_sell_sol NUMERIC(24, 9) DEFAULT 0,
    whale_buy_volume_sol NUMERIC(24, 9) DEFAULT 0,
    whale_sell_volume_sol NUMERIC(24, 9) DEFAULT 0,
    num_whale_buys INTEGER DEFAULT 0,
    num_whale_sells INTEGER DEFAULT 0,
    
    -- Dev-Tracking (Rug-Pull-Erkennung)
    dev_sold_amount NUMERIC(24, 9) DEFAULT 0,
    
    -- Erweiterte Metriken
    volatility_pct NUMERIC(10, 4) DEFAULT 0,
    avg_trade_size_sol NUMERIC(24, 9) DEFAULT 0,
    
    -- Ratio-Metriken
    buy_pressure_ratio NUMERIC(5, 4) DEFAULT 0,
    unique_signer_ratio NUMERIC(5, 4) DEFAULT 0
);

-- Indizes
CREATE INDEX IF NOT EXISTS idx_metrics_mint_time ON coin_metrics(mint, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_metrics_timestamp ON coin_metrics(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_metrics_phase ON coin_metrics(phase_id_at_time);
CREATE INDEX IF NOT EXISTS idx_metrics_koth ON coin_metrics(is_koth) WHERE is_koth = TRUE;